---
- hosts: all

  vars_files:
    - defaults/main.yml

  pre_tasks:
    - set_fact: install_postgres=yes

  tasks:
    - import_tasks: tasks/main.yml

  handlers:
    - import_tasks: handlers/main.yml
