---
- name: Start PostgreSQL
  service: name=postgresql state=started enabled=yes
  become: yes

- name: Create Administrator
  postgresql_user:
    name:            "{{ db_admin }}"
    password:        "{{ db_pass }}"
    encrypted:       yes
    state:           present
    role_attr_flags: SUPERUSER
  become: yes
  become_user: postgres

- name: Copy pg_hba Config
  template:
    src:  pg_hba.conf.j2
    dest: /etc/postgresql/{{ postgres_version }}/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode:  0640
  become: yes
  register: pg_hba_result

- name: Restart PostgreSQL
  service: name=postgresql state=restarted
  become: yes
  when: pg_hba_result | changed
