---
- name: Create Administrator
  postgresql_user:
    name:            "{{ db_admin }}"
    password:        "{{ db_pass }}"
    encrypted:       yes
    state:           present
    role_attr_flags: SUPERUSER,CREATEDB,CREATEROLE,REPLICATION
  become: yes
  become_user: postgres

- name: Require Password Authentication
  lineinfile:
    name: /etc/postgresql/{{ postgres_version }}/main/pg_hba.conf
    regexp: (local\s+all\s+all\s+)peer
    line: \1md5
    state: present
    backrefs: yes
  become: yes
  register: pg_hba_result
  notify: Restart PostgreSQL

- name: Restart PostgreSQL
  service: name=postgresql state=restarted
  become: yes
  when: pg_hba_result | changed
