---
- name: Create Administrator
  postgresql_user:
    name:            "{{ postgres_admin }}"
    password:        "{{ postgres_pass }}"
    encrypted:       yes
    state:           present
    role_attr_flags: SUPERUSER,CREATEDB,CREATEROLE,REPLICATION
  become: yes
  become_user: postgres

- name: Require Password Authentication
  lineinfile:
    name: /etc/postgresql/9.3/main/pg_hba.conf
    regexp: (local\s+all\s+{{ item }}\s+)peer
    line: \1md5
    state: present
    backrefs: yes
  with_items:
    - postgres
    - all
  become: yes
  notify: Restart PostgreSQL

  # is this maybe silly? Probably. Will it solve Travis? Maybe?
- name: Restart PostgreSQL
  service: name=postgresql state=restarted
  become: yes

- name: Disable Login for postgres User
  postgresql_user:
    name:            postgres
    db:              postgres
    role_attr_flags: NOLOGIN
    login_user:     "{{ postgres_admin }}"
    login_password: "{{ postgres_pass }}"
