---
- name: Install Postgres
  include_tasks: install.yml
  when: install_postgres

- name: Add Adminpack
  postgresql_ext:
    name: adminpack
    db:   postgres
    login_user:     "{{ db_admin }}"
    login_password: "{{ db_pass }}"

- name: Create or Update User
  include_tasks: user.yml
  when: new_db_user is defined and new_db_pass is defined

- name: Create or Modify Database
  include_tasks: database.yml
  when: new_db_name is defined

- name: Modify User Privileges
  include_tasks: privs.yml
  when: new_db_priv is defined
