---
- name: Install
  apt: package={{ item }} state=present
  with_items:
    - postgresql-{{ postgres_version }}
    - postgresql-contrib-{{ postgres_version }}
    - python-psycopg2
  become: yes
  register: postgres_install

- include: lockdown.yml
  when: postgres_install | changed

- name: Add Adminpack
  postgresql_ext:
    name: adminpack
    db:   postgres
    login_user:     "{{ postgres_admin }}"
    login_password: "{{ postgres_pass }}"
