---
- name: Create User
  postgresql_user:
    name:            "{{ new_db_user }}"
    password:        "{{ new_db_pass }}"
    db:              postgres
    encrypted:       yes
    login_user:      "{{ db_admin }}"
    login_password:  "{{ db_pass }}"
    state:           present
    role_attr_flags: "{{ '' if new_db_name is defined else 'SUPERUSER' }}"
